### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sewwolf** [sewwolf/protospace-36825#1]
#URL
https://protospace-36825.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **正しくプロトタイプが編集できた場合は、詳細ページへ遷移するようにしましょう**
トップページに遷移してしまいます。

- [ ] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう**
以下のエラーページに遷移してしまいます。
<img width="629" alt="スクリーンショット 2021-12-05 9 31 22" src="https://user-images.githubusercontent.com/62644781/144728902-9b3f716d-7a10-4e06-b7f5-9d4c288133d8.png">

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
コメントの投稿者名をクリックしたときに遷移しません。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by sewwolf** [comment]
ありがとうございます。最終確認の際にherokuに反映させるのを忘れていたみたいです。
完了報告の提出をします。

**Comment by mo1015** [comment]
ご提出ありがとうございます！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！
